// models/propiedad.js
const {Schema, model} = require('mongoose');

const propiedadCollection = "Propiedad"

const propiedadSchema = Schema({
  tipo: String,
  id: String,
  Inmobiliaria: {
    nombre: String,
    codigo: String,
    email: String,
    direccion: String,
    telefono: String,
    celular: String,
    sucursal: Number,
    logo: String
  },
  Broker: {
    id: Number,
    nombre: String,
    telefono: String,
    email: String,
    foto: String
  },
  enVenta: String,
  enAlquiler: String,
  titulo: String,
  descripcion: String,
  Ubicacion: {
    departamento: String,
    ciudad: String,
    barrio: String,
    distanciamarmetros: String,
    frentealmar: String,
    direccion: String,
    lat: String,
    lon: String
  },
  Caracteristicas: {
    parrillero: String,
    playroom: String,
    mucamas: String,
    servicioplaya: String,
    tipoedificio: String,
    asensores: String,
    piscina: String,
    estacionamientovisitas: String,
    sauna: String,
    gimnasio: String,
    canchas: String,
    vigilancia: String,
    numeropiso: String,
    aptosxpiso: String,
    cantidadpisos: String,
    totaldormitorios: String,
    mediodormitorio: String,
    banos: String,
    suites: String,
    toilettes: String,
    cocina: String,
    living: String,
    comedor: String,
    livingcomedor: String,
    capacidadpersonas: String,
    cantidadcamas: String,
    caracteristicas: String,
    equipamiento: String,
    comodidades: String,
    amenities: String,
    monedacontribucion: String,
    contribucioninmobiliaria: String,
    frecuenciacontribucion: String,
    monedaprimaria: String,
    impuestoprimaria: String,
    frecuenciaprimaria: String,
    gastoscomunes: String,
    monedagastos: String,
    frecuenciagastos: String,
    antiguedad: String,
    dependenciaservicio: String,
    banoservicio: String,
    estufalena: String,
    cochera: String,
    garage: String,
    estacionamiento: String,
    estado: String,
    calefaccion: String,
    superficietotal: String,
    superficiepropia: String,
    superficiecubierta: String,
    superficiesemicubierta: String,
    superficiebalcon: String,
    baulera: String,
    lavadero: String,
    EsPH: String,
    muebles: String,
    amoblado: String,
    amovred: String,
    terrazabalcon: String,
    comedordiario: String,
    vista: String,
    tenencia: String,
    orientacion: String,
    disposicion: String,
    idedificio: String,
    fondoreserva: String,
    monedafondo: String,
    vigenciafondo: String,
    youtube: String,
    matterport: String
  },
  destacada: Number,
  venta: {
    precio: String,
    mda: String,
    fechavigencia: String,  // Considera usar Date si prefieres
    permuta: String,
    oferta: String,
    financia: String,
    renta: String,
    porcentajerenta: String,
    saldobanco: String
  },
  alquiler: {
    VigenciaAlquiler: String,  // Considera usar Date si prefieres
    PrecioPubliacionAlquiler: String,
    Enero: String,
    EneroQuincena1: String,
    EneroQuincena2: String,
    Febrero: String,
    FebreroQuincena1: String,
    FebreroQuincena2: String,
    Reveion: String,
    Carnaval: String,
    SemanaSanta: String,
    AnualPesos: String,
    InvernalPesos: String,
    AnualDolares: String,
    PeriodoPrecioAlqAnual: String,
    AnualTestigo: String,
    CotizacionDolar: String,
    InvernalDolares: String,
    Diciembre: String,
    DiciembreQuincena1: String,
    DiciembreQuincena2: String,
    Marzo: String,
    MarzoQuincena1: String,
    MarzoQuincena2: String,
    Temporada: String,
    AceptaMascota: String,
    AceptaFumador: String,
    AceptaNinos: String,
    GDeposito: String,
    GPropiedad: String,
    GAnda: String,
    GPorto: String,
    GCGN: String,
    GMVOTMA: String,
    GSura: String,
    GLUC: String,
    GCIncluidos: String
  },
  fotos: [{
    url: String,
    descripcion: String
  }],
  url: String
});

propiedadModel = model(propiedadCollection, propiedadSchema);
module.exports = { propiedadModel }
